### PR TITLE
Changes module.exports to be export default.

### PR DESCRIPTION
**Pull request by blueflash2o**
Was getting an module.exports is read only error.

### CODE REVIEW

**Review by marcodpt — COMMENTED** [review]
Sorry for my ignorance... but what is the diference in each use case?

**Comment by blueflash2o** [comment]
I don't know. I was getting a runtime error with vue-cli and vue 2.5.17 and it was complaining about module.exports being read only. This fixed it for me.

Digging into it a little more I think it might be a webpack issue. An issue like https://github.com/webpack/webpack/issues/3997 from https://github.com/webpack/webpack/releases/tag/v2.2.0-rc.5
But I am unsure if those are the exact cause. It seems like it might be.

**Comment by marcodpt** [comment]
I use webpack, and i have no problems with module.exports.
In the past I google about the differences and I thought the module.exports was the best choice.
But I don't remember why.... :-)

**Comment by marcodpt** [comment]
I view some vue components that use exports default
https://github.com/sagalbot/vue-select/blob/master/src/index.js
https://github.com/ratiw/vuetable-2/blob/master/src/index.js
I think you are right... I will accept it!

**Pull request merged**
